MascotasApp/MascotasApp/Models/Mascota.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MascotasApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Raza { get; set; }
        public Nullable<int> Edad { get; set; }
        public string NombreDueno { get; set; }
    }
}

MascotasApp/MascotasApp/Models/MascotasContext.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MascotasApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MascotasConnection : DbContext
    {
        public MascotasConnection()
            : base("name=MascotasConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mascota> Mascota { get; set; }
    }
}

MascotasApp/MascotasApp/Models/MascotasContext.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\NINVIC\source\repos\MascotasApp_ASP_NETFramework\MascotasApp\MascotasApp\Models\MascotasContext.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

MascotasApp/MascotasApp/Models/MascotasContext.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

MascotasApp/MascotasApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MascotasApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MascotasApp/MascotasApp/Controllers/MascotaController.cs
using MascotasApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MascotasApp.Controllers
{
    public class MascotaController : Controller
    {
        //const string nombreSesion = "ListadoMascota"; PARA TRABAJAR CON VARIABLES DE SESSION
        private MascotasConnection BD;

        public MascotaController()
        {
            BD = new MascotasConnection();
        }
        public ActionResult Index()
        {
            var listado = BD.Mascota.ToList();
            return View(listado);

            //if (Session[nombreSesion] == null)
            //{
            //    var listadoMascotas = ObtenerMascotas();
            //    Session[nombreSesion] = listadoMascotas;
            //    return View(listadoMascotas);
            //}
            //else
            //{
            //    var listadoMascotas = (List<Mascota>)Session[nombreSesion];
            //    return View(listadoMascotas.OrderBy(x=> x.Id).ToList());
            //}
        }

        public ActionResult Nuevo()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(Mascota mascota)
        {
            BD.Mascota.Add(mascota);
            BD.SaveChanges();
            //var listadoMascotas = (List<Mascota>)Session[nombreSesion];
            //listadoMascotas.Add(mascota);
            //Session[nombreSesion] = listadoMascotas;
            return RedirectToAction("Index");
        }
        //private List<Mascota> ObtenerMascotas()
        //{
        //    var Listado = new List<Mascota>();
        //    Listado.Add(new Mascota { Id = 1, Edad = 2, Nombre = "Trusty", NombreDueno = "Nini", Raza = "Perro" });
        //    Listado.Add(new Mascota { Id = 2, Edad = 8, Nombre = "Tonti", NombreDueno = "victor", Raza = "Gato" });
        //    Listado.Add(new Mascota { Id = 3, Edad = 1, Nombre = "Paco", NombreDueno = "Maria", Raza = "Loro" });

        //    return Listado;
        //}

        public ActionResult Actualizar(int id)
        {
            var mascota = BD.Mascota.FirstOrDefault(x => x.id == id);
            return View(mascota);

            //var listadoMascotas = (List<Mascota>)Session[nombreSesion];
            //var mascota = listadoMascotas.FirstOrDefault(x => x.Id == id);
            //return View(mascota);
        }

        [HttpPost]
        public ActionResult Actualizar(Mascota mascota)
        {
            var mascotaActualizar = BD.Mascota.FirstOrDefault(x => x.id == mascota.id);
            mascotaActualizar.Edad = mascota.Edad;
            mascotaActualizar.Nombre = mascota.Nombre;
            mascotaActualizar.NombreDueno = mascota.NombreDueno;
            mascotaActualizar.Raza = mascota.Raza;

            BD.SaveChanges();
            return RedirectToAction("Index");

            //var listadoMascotas = (List<Mascota>)Session[nombreSesion];
            //var mascotaActualizar = listadoMascotas.FirstOrDefault(x => x.Id == mascota.Id);
            //listadoMascotas.Remove(mascotaActualizar);
            //listadoMascotas.Add(mascota);
            //return RedirectToAction("Index");
        }

        public ActionResult Eliminar(int id)
        {
            var mascotaEliminar = BD.Mascota.FirstOrDefault(x => x.id == id);
            BD.Mascota.Remove(mascotaEliminar);
            BD.SaveChanges();
            return RedirectToAction("Index");
            //var listadoMascotas = (List<Mascota>)Session[nombreSesion];
            //var mascotaActualizar = listadoMascotas.FirstOrDefault(x => x.Id == id);
            //listadoMascotas.Remove(mascotaActualizar);
            //return RedirectToAction("Index");
        }
    }
}

MascotasApp/MascotasApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MascotasApp/MascotasApp/Views/Mascota/Actualizar.cshtml
@model MascotasApp.Models.Mascota
@{
    ViewBag.Title = "Actualizar";
}

<h2>Actualizar Mascota</h2>
<hr />

<form action="@Url.Action("Actualizar","Mascota")" method="post">
    <div class="form-group">
        <label>ID</label>
        @Html.TextBoxFor(x => x.id, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Raza</label>
        @Html.TextBoxFor(x => x.Raza, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Edad</label>
        @Html.TextBoxFor(x => x.Edad, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Nombre dueño</label>
        @Html.TextBoxFor(x => x.NombreDueno, new { @class = "form-control", @required = "required" })
    </div>
    <div>
        <input type="submit" value="Guardar" class="btn btn-success" />
        <a href="@Url.Action("Index","Mascota")" class="btn btn-danger">Regresar</a>
    </div>
</form>

MascotasApp/MascotasApp/Views/Mascota/Index.cshtml
@model List<MascotasApp.Models.Mascota>
@{
    ViewBag.Title = "Index";
}

<h2>
    <a href="@Url.Action("Nuevo","Mascota")" class="btn btn-success right" style="float:right;">Nuevo</a>
    Listado de Mascotas
</h2>
<hr/>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Raza</th>
            <th>Edad</th>
            <th>Nombre dueño</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var mascota in Model)
        {
            <tr>
                <td>@mascota.id</td>
                <td>@mascota.Nombre</td>
                <td>@mascota.Raza</td>
                <td>@mascota.Edad</td>
                <td>@mascota.NombreDueno</td>
                <td>
                    <a href="@Url.Action("Actualizar","Mascota", new { id = mascota.id })" class="btn btn-primary">Actualizar</a>
                    <a href="@Url.Action("Eliminar","Mascota", new { id = mascota.id })" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
        }      
    </tbody>
</table>

MascotasApp/MascotasApp/Views/Mascota/Nuevo.cshtml
@model MascotasApp.Models.Mascota
@{
    ViewBag.Title = "Nuevo";
}

<h2>Nueva Mascota</h2>
<hr/>

<form action="@Url.Action("Nuevo","Mascota")" method="post">
    <div class="form-group">
        <label>ID</label>
        @Html.TextBoxFor(x => x.id, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Nombre</label>
        @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Raza</label>
        @Html.TextBoxFor(x => x.Raza, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Edad</label>
        @Html.TextBoxFor(x => x.Edad, new { @class = "form-control", @required = "required" })
    </div>
    <div class="form-group">
        <label>Nombre dueño</label>
        @Html.TextBoxFor(x => x.NombreDueno, new { @class = "form-control", @required = "required" })
    </div>
    <div>
        <input type="submit" value="Guardar" class="btn btn-success" />
        <a href="@Url.Action("Index","Mascota")" class="btn btn-danger">Regresar</a>
    </div>
</form>

MascotasApp/MascotasApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MascotasApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MascotasApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Mascotas", "Index", "Mascota")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MascotasApp</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>